stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install

deploy:
  stage: deploy
  image: python:3.7
  script:
    - apt-get update && apt-get install -y zip
    - zip -r lambda.zip target/*    # Assuming your JAR file is generated in the 'target' directory
    - pip install awscli
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda.zip --region $AWS_REGION
  only:
    - main
