stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install

deploy:
  stage: deploy
  image: python:3.7
  script:
    - apt-get update && apt-get install -y zip
    - zip -r $CI_PROJECT_NAME.zip *    
    - pip install awscli
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$CI_PROJECT_NAME.zip --region $AWS_REGION
  only:
    - main
