stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.8.1-openjdk-11
  script:
    - mvn clean install

deploy:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://target/my-app.jar --region $AWS_REGION
