stages:
  - archiving
  - build
  - deploy

archive:
  stage: archiving

  before_script:
    - apt-get update
    - apt-get install zip -y

  script:
    - echo "Archiving lambda code"
    - zip -r $CI_PROJECT_NAME.zip *

  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip


build:
  stage: build
  image: maven:3.8.1-openjdk-11
  script:
    - mvn clean install

deploy:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$CI_PROJECT_NAME.zip --region $AWS_REGION
